import 'package:flutter/material.dart';

// ignore: must_be_immutable
class Duzen extends StatelessWidget {
  Duzen({Key? key}) : super(key: key);
  List<String> yazi = [
    "Andromeda ",
    " Pompa ",
    " Cennetkuşu ",
    " Kova ",
    " Kartal ",
    " Sunak ",
    " Koç ",
    " Arabacı ",
    " Çoban ",
    " Çelikkalem ",
    " Zürafa ",
    " Yengeç ",
    " Av Köpekleri ",
    " Büyük Köpek ",
    " Küçük Köpek ",
    " Oğlak ",
    " Karina ",
    " Koltuk ",
    " Erboğa ",
    " Kral ",
    " Balina ",
    " Bukalemun ",
    " Pergel ",
    " Güvercin ",
    " Berenis’in Saçı ",
    " Güneytacı ",
    " Kuzeytacı ",
    " Karga ",
    " Kupa ",
    " Güneyhaçı ",
    " Kuğu ",
    " Yunus ",
    " Kılıçbalığı ",
    " Ejderha ",
    " Tay ",
    " Irmak ",
    " Ocak ",
    " İkizler ",
    " Turna ",
    " Herkül ",
    " Saat ",
    " Suyılanı ",
    " Küçüksuyılanı ",
    " Hintli ",
    " Kertenkele ",
    " Aslan ",
    " Küçük Aslan ",
    " Tavşan ",
    " Terazi ",
    " Kurt ",
    " Vaşak ",
    " Çalgı ",
    " Masa ",
    " Mikroskop ",
    " Tekboynuz ",
    " Sinek ",
    " Cetvel ",
    " Sekizlik ",
    " Yılancı ",
    " Avcı ",
    " Tavus ",
    " Kanatlıat ",
    " Kahraman ",
    " Anka ",
    " Ressam ",
    " Balık ",
    " Güneybalığı ",
    " Pupa ",
    " Kumpas ",
    " Ağcık ",
    " Okçuk ",
    " Yay ",
    " Akrep ",
    " Heykeltraş ",
    " Kalkan ",
    " Yılan ",
    " Altılık ",
    " Boğa ",
    " Dürbün ",
    " Üçgen ",
    " Güney Üçgeni ",
    " Tukan ",
    " Büyük Ayı ",
    " Küçük Ayı ",
    " Yelken ",
    " Başak ",
    " Uçanbalık ",
    " Tilkicik"
  ];
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
